### ISSUE TITLE
Machine position error

### ISSUE THREAD

**Issue by mrakrmakmrka** [digger1213/CruiserImproved#13]
Your mod has a very strange behavior of the machine, namely: the machine always faces away from the magnet (the screenshot shows it). This happens always when “Save Cruiser Values” is disabled in the config. And it disturbs very much. But, if you play with “Save Cruiser Values” enabled, yes, the car takes the last position from the saved file, but there is also a problem, if the car is even slightly warped, this one will be saved too. In vanilla version the car no matter how it is parked to the magnet, even blown up, when restarting - it always faces the magnet and is always perfectly evenly parked at the magnet. Be so kind, fix this feature and make it like in vanilla version, that is, remove it altogether.

![20240829213149_1](https://github.com/user-attachments/assets/8e2670f4-fb68-41d1-b032-3641f516bb5c)

**Comment by mrakrmakmrka** [comment]
Also, found another oddity, just with your mod, the car is NOT magnetized on the left side (ie, as in vanilla, facing the magnet), in order to fix it, you have to repeatedly turn off and turn on the magnet. But the right side (as on the screenshot) magnetizes immediately, which is wrong.

**Comment by digger1213** [comment]
I've fixed the cruiser starting facing the wrong way with 'Save Cruiser Values' disabled in [1.4.1](https://github.com/digger1213/CruiserImproved/releases/tag/v1.4.1), so it will now match vanilla. The cruiser saving attachment rotation with that config option enabled is intentional however and hasn't been changed.

**Comment by mrakrmakmrka** [comment]
@digger1213 

Thank you!
