### ISSUE TITLE
Cannot access ignition

### ISSUE THREAD

**Issue by Enterprise12nx01** [digger1213/CruiserImproved#3]
I cannot access the ignition key when in the drivers seat. i have no other cruiser mods and even tried turning off letmelookdown.
ill try using it with no other mods and report back.
cruiser is unusable with this issue though as i cannot start the car

**Comment by digger1213** [comment]
Do you have any emote mods like TooManyEmotes? Some mods that change the player animator can cause players to stand up in the seat.
