### ISSUE TITLE
[Bug] Company Cruiser spawns in the wrong direction after reloading a save

### ISSUE THREAD

**Issue by zndrmn** [digger1213/CruiserImproved#4]
I part the cruiser facing the switch and reloading caused it to face the opposite direction

![1966720_20240714184707_1](https://github.com/user-attachments/assets/97843ed7-0f45-4249-9b63-1969cd4bcaae)

**Comment by digger1213** [comment]
This is a vanilla issue, as the game does not save any information about the position the Cruiser is in so it'll always be in the same spot (with minor randomization) after reloading. I don't see this as being too important but I'll look into it and implement a fix if it can be done easily enough and without breaking the save file when the mod isn't loaded.

**Comment by digger1213** [comment]
This has now been implemented in [v1.3.0](https://github.com/digger1213/CruiserImproved/releases/tag/v1.3.0). The cruiser now saves magnet position as well as turbos and ignition state.
