### ISSUE TITLE
Monsters not spawn?

### ISSUE THREAD

**Issue by Lizena2314** [digger1213/CruiserImproved#5]
Idk why it is happening but when i set "Prevent Passengers Eject Driver" to true the game doesnt spawn monsters and i was using a mod menu, it was working perfect but when i set it to true the mod menu always says "you need to be server host to use this command" please fix this.

**Comment by Lizena2314** [comment]
+ This issue shows only when i play with squad.

**Comment by digger1213** [comment]
This is very strange, could you send the host's LogOutput.log file (in the BepInEx folder of your mod manager profile/game installation folder) after a session where this happens? I can't think of any way this setting specifically could cause enemies to fail to spawn.

**Comment by Lizena2314** [comment]
[LogOutput.log](https://github.com/user-attachments/files/16322457/LogOutput.log)

Idk it contains yesterdays logs but here you go.

**Comment by dopadream** [comment]
> [LogOutput.log](https://github.com/user-attachments/files/16322457/LogOutput.log)
> 
> Idk it contains yesterdays logs but here you go.

This log shows that mouthdogs were spawning and existed on the map

**Comment by Lizena2314** [comment]
Only mouthdogs? Because normally in the map oldbirds, giants, mouthdogs, leviathans, thumpers and etc. will need to spawn but i didnt see any mob while playing with this issue, and also when the issue shows up i was playing with multiple mods maybe they can cause this issue.

**Comment by dopadream** [comment]
I didn't look. I just ctrl f and saw that mouthdogs existed. You can probably check for yourself easily. That being said, yes, I'm pretty sure this is a conflict with this and some other mod(s)? But it's really uncertain

**Comment by digger1213** [comment]
I've just released [v1.2.2](https://github.com/digger1213/CruiserImproved/releases/tag/v1.2.2) that should fix problems like this. There was an issue preventing entities from spawning when reloading a save with a Cruiser, and although I could not find the exception that causes this in your log file, your case sounds similar enough that hopefully this version will fix your problem. Update your mod and let me know if your issue persists, with another log file from the host if possible.

**Comment by Lizena2314** [comment]
Okay thanks if nothing changes i will update.

**Comment by Lizena2314** [comment]
Hey @digger1213 can i add you from discord? i need help for making lethal company mods.

**Comment by digger1213** [comment]
The [Lethal Company Modding discord](https://discord.gg/XeyYqRdRGC) is a good place to ask for modding help, you can find me at my [mod's thread](https://discord.com/channels/1168655651455639582/1258980772996448309) there.

**Comment by digger1213** [comment]
Closing as the issue appears to be solved since v1.2.2.
