### ISSUE TITLE
LCVR incompatible

### ISSUE THREAD

**Issue by TinyDerp** [digger1213/CruiserImproved#7]
Breaks the view model making you a 10 ft tall giant.
![20240731144559_1](https://github.com/user-attachments/assets/9a3820bd-470d-47a4-8d84-86b34a98dd99)

**Comment by digger1213** [comment]
This is probably due to the changes I made to the camera for the lean and seat boost features. Turning these features off in the config likely won't fix this issue due to my implementation though so I'll look into fixing this for the next version.

**Comment by digger1213** [comment]
This is now fixed now in [v1.4.0](https://github.com/digger1213/CruiserImproved/releases/tag/v1.4.0).
